version: '3'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pergamum-api
    container_name: pergamum-api
    ports:
      - "5000:8080"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
